# Generated by Django 2.2.2 on 2020-05-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('-pk',), 'verbose_name_plural': 'galleries'},
        ),
    ]
