# Generated by Django 2.2.2 on 2020-05-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('created_date', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='events')),
                ('story', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('created_date', models.DateField(auto_now=True)),
                ('story', models.TextField()),
            ],
        ),
    ]
