# Generated by Django 2.2.2 on 2020-05-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ('-pk',), 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='legal',
            options={'ordering': ('-pk',), 'verbose_name_plural': 'legals'},
        ),
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.SlugField(blank=True, default='mansih', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='slug',
            field=models.SlugField(blank=True, default='mansih', max_length=255, null=True),
        ),
    ]
